BASE_URL = "https://www.useinsider.com/"
QA_URL = "https://useinsider.com/careers/quality-assurance/"
INSIDER_LOGO_XPATH = "//a[@class='navbar-brand d-flex flex-row align-items-center']//img"
COMPANY_XPATH = "/html/body/nav/div[2]/div/ul[1]/li[6]/a"
CAREERS_XPATH = "/html/body/nav/div[2]/div/ul[1]/li[6]/div/div[2]/a[2]"
CAREERS_TEAM_ID = "career-find-our-calling"
CAREERS_LOCATION_ID = "career-our-location"
CAREERS_LIFE_AT_INSIDER_XPATH = "/html/body/div[1]/section[4]"
SEE_ALL_QA_JOBS_BUTTON_XPATH = "//*[@id='page-head']/div/div/div[1]/div/div/a"
LOCATIONS_FILTER_XPATH = "//*[@id='top-filter-form']/div[1]/span/span[1]/span/span[2]/b"
ISTANBUL_LOCATION_XPATH = "//li[contains(text(), 'Istanbul, Turkey')]"
POSITION_LIST_ITEM_CLASSNAME = "position-list-item"
DEPARTMENT_CONTAINER_XPATH = "//*[@id='select2-filter-by-department-container']"
DEPARTMENT_POSITION_CLASSNAME = "position-department"
LOCATION_POSITION_CLASSNAME = "position-location"
VIEW_ROLE_BUTTON_XPATH = "//*[@id='jobs-list']/div[1]/div/a"
LEVER_APP_URL = "https://jobs.lever.co/useinsider/78ddbec0-16bf-4eab-b5a6-04facb993ddc"